# Generated by Django 2.2 on 2019-04-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
